<?php
$extensionPath = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('tcdirectmail');
return array(
	'tx_tcdirectmail_scheduler' => $extensionPath . 'class.tx_tcdirectmail_scheduler.php',
    'tx_tcdirectmail_click' => $extensionPath . 'eid/class.tx_tcdirectmail_click.php',
    'tx_tcdirectmail_tools' => $extensionPath . 'class.tx_tcdirectmail_tools.php',
    'tx_tcdirectmail_target_array' => $extensionPath . 'class.tx_tcdirectmail_target_array.php',
    'tx_tcdirectmail_target_beusers' => $extensionPath . 'class.tx_tcdirectmail_target_beusers.php',
    'tx_tcdirectmail_target_csvfile' => $extensionPath . 'class.tx_tcdirectmail_target_csvfile.php',
    'tx_tcdirectmail_target_csvlist' => $extensionPath . 'class.tx_tcdirectmail_target_csvlist.php',
    'tx_tcdirectmail_target_csvurl' => $extensionPath . 'class.tx_tcdirectmail_target_csvurl.php',
    'tx_tcdirectmail_target_fegroups' => $extensionPath . 'class.tx_tcdirectmail_target_fegroups.php',
    'tx_tcdirectmail_target_fepages' => $extensionPath . 'class.tx_tcdirectmail_target_fepages.php',
    'tx_tcdirectmail_target_gentlesql' => $extensionPath . 'class.tx_tcdirectmail_target_gentlesql.php',
    'tx_tcdirectmail_target_html' => $extensionPath . 'class.tx_tcdirectmail_target_html.php',
    'tx_tcdirectmail_target' => $extensionPath . 'class.tx_tcdirectmail_target.php',
    'tx_tcdirectmail_target_rawsql' => $extensionPath . 'class.tx_tcdirectmail_target_rawsql.php',
    'tx_tcdirectmail_target_sql' => $extensionPath . 'class.tx_tcdirectmail_target_sql.php',
    'tx_tcdirectmail_target_ttaddress' => $extensionPath . 'class.tx_tcdirectmail_target_ttaddress.php',
    'tx_tcdirectmail_mailer' => $extensionPath . 'class.tx_tcdirectmail_mailer.php',
    'tx_tcdirectmail_scheduler' => $extensionPath . 'class.tx_tcdirectmail_scheduler.php',
    'tx_tcdirectmail_plain' => $extensionPath . 'class.tx_tcdirectmail_plain.php',
    'tx_tcdirectmail_plain_template' => $extensionPath . 'class.tx_tcdirectmail_plain_template.php',
    'tx_tcdirectmail_plain_html2text' => $extensionPath . 'class.tx_tcdirectmail_plain_html2text.php',
    'tx_tcdirectmail_plain_simple' => $extensionPath . 'class.tx_tcdirectmail_plain_simple.php',
    'tx_tcdirectmail_plain_lynx' => $extensionPath . 'class.tx_tcdirectmail_plain_lynx.php',
    'tx_tcdirectmail_bouncehandler' => $extensionPath . 'class.tx_tcdirectmail_bouncehandler.php',
    'tx_tcdirectmail_section_targets' => $extensionPath . 'section/class.tx_tcdirectmail_section_targets.php',
    'tx_tcdirectmail_section_modulefunction' => $extensionPath . 'section/class.tx_tcdirectmail_section_modulefunction.php',
    'tx_tcdirectmail_controller_modulecontroller' => $extensionPath . 'Classes/Controller/ModuleController.php',
);

